name: Test pnpm caching
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "20 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pnpm:
    runs-on:
      - namespace-profile-e2e-small
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.6.2"
      - uses: actions/checkout@v3
        with:
          repository: namespace-integration-demos/cache-pnpm-workspace
          path: demo
      - name: Setup pnpm cache
        uses: ./ # Uses an action in the root directory
        with:
          cache: pnpm
          path: |
            ./node_modules/.cache
      - run: pnpm install
        working-directory: ./demo/fullstack

      - name: Print cache metadata file
        run: |
          ls -al /cache/.ns
          cat /cache/.ns/cache-metadata.json
